WINDOW_CLOSE   			    = 1
CLOSE_YOURSELF 			    = 2
BUTTON_CLICKED			    = 3
CTRL_KEY_CHANGE             = 4
OPTIMISATION_UPDATE         = 5
SCATTERPLOT_LEFT_CLICK      = 6
SCATTERPLOT_RIGHT_CLICK     = 7
SCATTERPLOT_HOVER           = 8
